apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- serviceaccount.yaml
- certificate.yaml
- configmap.yaml
# - role.yaml  may not be needed .... 
# - rolebinding.yaml

images:
- name: oidc
  newName: contour-authserver
  newTag: latest
