apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- serviceaccount.yaml
- certificate.yaml

images:
- name: controller
  newName: contour-authserver
  newTag: contour-ext-auth-0-ge6509e6
- name: testserver
  newName: contour-authserver
  newTag: latest
