name: Pull Request

on: [pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ^1.20
    - run: go mod download
    - name: build
      run: make build
    - name: lint
      run: make lint
    - name: test
      run: make check
